production:
  # replace this with a random string of at least 20 characters
  encryption_key: rzymV8W5mmxJ0xAB5ovXvDWHbXc=

development:
  encryption_key: rzymV8W5mmxJ0xAB5ovXvDWHbXc=

test:
  encryption_key: rzymV8W5mmxJ0xAB5ovXvDWHbXc=
